/********** PLANTS ACTION TYPES *************** */

export const FETCH_PLANETS_STARTED = "FETCH_PLANETS_STARTED";
export const FETCH_PLANETS_END = "FETCH_PLANETS_END";
export const FETCH_PLANETS_FAILURE = "FETCH_PLANETS_FAILURE";
export const FETCH_PLANETS_SUCCESS = "FETCH_PLANETS_SUCCESS";

export const FETCH_STAR_SHIPS_STARTED = "FETCH_STAR_SHIPS_STARTED";
export const FETCH_STAR_SHIPS_END = "FETCH_STAR_SHIPS_END";
export const FETCH_STAR_SHIPS_FAILURE = "FETCH_STAR_SHIPS_FAILURE";
export const FETCH_STAR_SHIPS_SUCCESS = "FETCH_STAR_SHIPS_SUCCESS";
